-- How many orders are in the dataset?
SELECT COUNT(*) AS total_revenue
FROM sales_data

-- How many unique customers made purchases?
SELECT COUNT(DISTINCT CustomerID) AS unique_customers
FROM sales_data;

-- What is the total sales revenue?
SELECT SUM(TotalPrice) AS total_revenue
FROM sales_data;

-- What is the average order value?
SELECT AVG(TotalPrice) AS average_order_value
FROM sales_data;

-- Which products generated the highest sales?
SELECT Product,
SUM(TotalPrice) AS revenue
FROM sales_data
GROUP BY Product
ORDER BY revenue DESC;
 
-- Which payment method is used most?
SELECT PaymentMethod,
COUNT(*) AS total_orders
FROM sales_data
GROUP BY PaymentMethod
ORDER BY total_orders DESC;

-- Which referral source brought the most customers?
SELECT ReferralSource,
COUNT(*) AS customers
FROM sales_data
GROUP BY ReferralSource
ORDER BY customers DESC;

-- Which shipping addressreceived the most address?
SELECT ShippingAddress,
COUNT(*) AS orders
FROM sales_data
GROUP BY ShippingAddress
ORDER BY orders DESC;

-- What is the total revenue generated by each payment method?
SELECT PaymentMethod,
SUM(TotalPrice) AS revenue
FROM sales_data
GROUP BY PaymentMethod
ORDER BY revenue DESC;

-- Which orders used coupon codes?
SELECT *
FROM sales_data
WHERE CouponCode <> 'NULL';

-- How many orders were completed, shipped or cancelled?
SELECT OrderStatus,
COUNT(*) AS total_orders
FROM sales_data
GROUP BY OrderStatus
ORDER BY total_orders DESC;

-- What are the top 10 most expensive orders?
SELECT OrderID,
CustomerID,
Product,
TotalPrice
FROM sales_data
ORDER BY TotalPrice DESC
LIMIT 10;

-- Which products sell in the highest quantities?
SELECT Product,
SUM(Quantity) AS quantity_sold
FROM sales_data
GROUP BY Product
ORDER BY quantity_sold DESC;

-- Which customers spent the most money?
SELECT CustomerID,
SUM(TotalPrice) AS amount_spent
FROM sales_data
GROUP BY CustomerID
ORDER BY amount_spent;

--What is the average quantity per order/ per product?
SELECT AVG(Quantity) as average_quantity
FROM sales_data;

SELECT Product,
AVG(Quantity) AS average_quantity
FROM sales_data
GROUP BY Product
ORDER BY average_quantity;